development:
  adapter: 'postgresql'
  database: 'my_app_development'
  host: 'localhost'
  encoding: 'utf8'

test:
  adapter: 'postgresql'
  database: 'my_app_test'
  host: 'localhost'
  encoding: 'utf8'

production:
  adapter: 'postgresql'
  database_url: <%= ENV['DATABASE_URL'] %>
